dist: xenial
language: python
python:
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
  - 3.7
  - 3.7-dev
  # - 3.8-dev
  # - nightly
install:
  - make install-dev
  - pip install coveralls
script:
  - make clean test
after_success:
  - coveralls
